server:
  port: 8000

spring:
  application:
    name: SettingServer
  websocket:
    enabled: true
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      springframework:
        web: INFO
        web.socket: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

spring.security.jwt.secret: b156814eafb6af3b71e38809b301f413265dccd3cb7d60425cd135285a6cb364ea1035a5cc3e5dd612a666c59981e50c36d0509789e555111ef76c1fd1df11be
spring.security.jwt.accessExpiration: 3600000
spring.security.jwt.refreshExpiration: 86400000
spring.security.jwt.header: Authorization

spring.security.jwt.refresh.header: Refresh