server:
  port: 8000

spring:
  application:
    name: SettingServer
  datasource:
    url: jdbc:postgresql://localhost:5433/basic
    username: minseok
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgresSQLDialect
      format_sql: true
      show_sql: true
      default_batch_fetch_size: 100
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  websocket:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    gcp:
      bigquery:
        credentials:
          location: file:/Users/minthug/Desktop/ssh/focus-hangout-434407-r6-1cdc39386afe.json
      storage:
        bucket: test_bucket_project_8825

  security:
    jwt:
      secret: b156814eafb6af3b71e38809b301f413265dccd3cb7d60425cd135285a6cb364ea1035a5cc3e5dd612a666c59981e50c36d0509789e555111ef76c1fd1df11be
      access-expiration: 3600000  # 1 hour
      refresh-expiration: 86400000  # 24 hours
      header: Authorization
      refresh:
        header: Refresh

logging:
  level:
    org.springframework:
      web: INFO
      web.socket: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true