server:
  port: 8000

spring:
  application:
    name: SettingServer
  websocket:
    enabled: true
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      springframework:
        web: INFO
        web.socket: DEBUG