#FROM amazoncorretto:17
#WORKDIR /app
#COPY . .
#RUN ./gradlew clean build
#RUN cp /app/build/libs/SettingServer-0.0.1-SNAPSHOT.jar /app/SettingServer-0.0.1-SNAPSHOT.jar
#EXPOSE 8000
#CMD ["java", "-jar", "SettingServer-0.0.1-SNAPSHOT.jar"]
